#!/usr/bin/env cwl-runner

cwlVersion: v1.2
class: Workflow

requirements:
  SubworkflowFeatureRequirement: {}
  StepInputExpressionRequirement: {}
  InlineJavascriptRequirement: {}
  ScatterFeatureRequirement: {}
  MultipleInputFeatureRequirement: {}
  NetworkAccess:
    networkAccess: True
inputs:
  band:
    type: string
  date:
    type: string
  geography:
    type: string
  database:
    type: File
    default:
      class: File
      location: https://raw.githubusercontent.com/ForomePlatform/dorieh/refs/heads/main/examples/with-postgres/database.ini
  connection_name:
    type: string
    default: "localhost"

steps:
  extract_year:
    run: https://raw.githubusercontent.com/ForomePlatform/dorieh/main/src/cwl/parse_date.cwl
    in:
      date: date
    out:
      - year

  download:
    run: https://raw.githubusercontent.com/ForomePlatform/dorieh/main/src/cwl/download.cwl
    in:
      year: extract_year/year
      band: band
    out:
      - log
      - data
      - errors

  get_shapes:
    run: https://raw.githubusercontent.com/ForomePlatform/dorieh/main/src/cwl/get_shapes.cwl
    in:
      geo: geography
      year: extract_year/year
    out:
      - shape_files

  aggregate:
    run: https://raw.githubusercontent.com/ForomePlatform/dorieh/main/src/cwl/aggregate_daily.cwl
    in:
      geography: geography
      year: extract_year/year
      dates: date
      band: band
      input: download/data
      shape_files: get_shapes/shape_files
      strategy:
        valueFrom: default
    out:
      - log
      - data
      - errors

  initdb:
    run: https://raw.githubusercontent.com/ForomePlatform/dorieh/main/src/cwl/initcoredb.cwl
    in:
      database: database
      connection_name: connection_name
    out:
      - log
      - err

  ingest:
    run: https://raw.githubusercontent.com/ForomePlatform/dorieh/main/src/cwl/ingest.cwl
    in:
      depends_on: initdb/log
      registry:
        default:
          class: File
          location: "https://raw.githubusercontent.com/ForomePlatform/dorieh/main/doc/tutorial/climate/example1_model.yml"
      domain:
        valueFrom: "tutorial"
      table:
        valueFrom: "bronze_temperature"
      input: aggregate/data
      database: database
      connection_name: connection_name
    out:
      - log
      - errors

  build_silver:
    run: https://raw.githubusercontent.com/ForomePlatform/dorieh/main/src/cwl/create.cwl
    in:
      depends_on: ingest/log
      registry:
        default:
          class: File
          location: "https://raw.githubusercontent.com/ForomePlatform/dorieh/main/doc/tutorial/climate/example1_model.yml"
      domain:
        valueFrom: "tutorial"
      table:
        valueFrom: "silver_temperature"
      database: database
      connection_name: connection_name
    out:
      - log
      - errors

  build_gold:
    run: https://raw.githubusercontent.com/ForomePlatform/dorieh/main/src/cwl/create.cwl
    in:
      depends_on: build_silver/log
      registry:
        default:
          class: File
          location: "https://raw.githubusercontent.com/ForomePlatform/dorieh/main/doc/tutorial/climate/example1_model.yml"
      domain:
        valueFrom: "tutorial"
      table:
        valueFrom: "gold_temperature_by_state"
      database: database
      connection_name: connection_name
    out:
      - log
      - errors


outputs:
  ## Generated by dorieh.platform.util.cwl_collect_outputs from download.cwl:
  download_log:
    type: File?
    outputSource: download/log
  download_data:
    type: File?
    outputSource: download/data
  download_errors:
    type: File
    outputSource: download/errors
  ## Generated by dorieh.platform.util.cwl_collect_outputs from get_shapes.cwl:
  get_shapes_shape_files:
    type: File[]
    outputSource: get_shapes/shape_files
  ## Generated by dorieh.platform.util.cwl_collect_outputs from aggregate_daily.cwl:
  aggregate_log:
    type: File?
    outputSource: aggregate/log
  aggregate_data:
    type: File?
    outputSource: aggregate/data
  aggregate_errors:
    type: File
    outputSource: aggregate/errors

  initdb_log:
    type: File
    outputSource: initdb/log
  initdb_err:
    type: File
    outputSource: initdb/err

  ingest_log:
    type: File
    outputSource: ingest/log
  ingest_err:
    type: File
    outputSource: ingest/errors

  build_silver_log:
    type: File
    outputSource: build_silver/log
  build_silver_err:
    type: File
    outputSource: build_silver/errors

  build_gold_log:
    type: File
    outputSource: build_gold/log
  build_gold_err:
    type: File
    outputSource: build_gold/errors

