#!/usr/bin/env cwl-runner

cwlVersion: v1.2
class: Workflow

requirements:
  SubworkflowFeatureRequirement: {}
  StepInputExpressionRequirement: {}
  InlineJavascriptRequirement: {}
  ScatterFeatureRequirement: {}
  MultipleInputFeatureRequirement: {}
  NetworkAccess:
    networkAccess: True
inputs:
  band:
    type: string
  year:
    type: string
  geography:
    type: string

steps:
  download:
    run: https://raw.githubusercontent.com/ForomePlatform/dorieh/main/src/cwl/download.cwl
    in:
      year: year
      band: band
    out:
      - log
      - data
      - errors

  get_shapes:
    run: https://raw.githubusercontent.com/ForomePlatform/dorieh/main/src/cwl/get_shapes.cwl
    in:
      geo: geography
      year: year
    out:
      - shape_files

  aggregate:
    run: https://raw.githubusercontent.com/ForomePlatform/dorieh/main/src/cwl/aggregate_daily.cwl
    in:
      geography: geography
      year: year
      band: band
      input: download/data
      shape_files: get_shapes/shape_files
    out:
      - log
      - data
      - errors

outputs:
  ## Generated by dorieh.platform.util.cwl_collect_outputs from download.cwl:
  download_log:
    type: File?
    outputSource: download/log
  download_data:
    type: File?
    outputSource: download/data
  download_errors:
    type: File
    outputSource: download/errors
  ## Generated by dorieh.platform.util.cwl_collect_outputs from get_shapes.cwl:
  get_shapes_shape_files:
    type: File[]
    outputSource: get_shapes/shape_files
  ## Generated by dorieh.platform.util.cwl_collect_outputs from aggregate_daily.cwl:
  aggregate_log:
    type: File?
    outputSource: aggregate/log
  aggregate_data:
    type: File?
    outputSource: aggregate/data
  aggregate_errors:
    type: File
    outputSource: aggregate/errors

